### ISSUE TITLE
Cannot estimate stories with " in the name

### ISSUE THREAD

**Issue by dirv** [mateuadsuara/remote-estimations#10]
We can create stories with " in the name, but then it's not possible to estimate them: instead, an error is displayed saying with "Error: nonexistent_name".

**Comment by mateuadsuara** [comment]
Hey Daniel,

Thanks for reporting the issue!
I'm glad you're using the tool and is useful to you!

It should be solved now and deployed to the demo environment.

In case you're curious, here's the fix:
https://github.com/mateuadsuara/remote-estimations/commit/8d912cccc4a64a43550ddd81dcb81ef8cb915a55

Thanks for contributing!
